### PR TITLE
Do not close the `queued_tasks` channel during exit

### PR DESCRIPTION
**Pull request by justinmimbs**
Thank you for sharing this package! We noticed that it can cause Julia to hang on exit, and it seems to hang during the attempt to close the `queued_tasks` channel. We probably don't need to close the channel explicitly since we're exiting, so removing the call to `close` seemed the simplest fix.

The hanging seems to occur when there is more work to do after closing the channel. Here is a minimum example to reproduce the issue.

```julia
using SentryIntegration

atexit(() -> @info "exiting")
SentryIntegration.init("fake")
exit()
```

### CODE REVIEW

**Comment by pengwyn** [comment]
Thanks! I want to merge this straight in, but I'm vaguely remembering a reason for this wait in the first place. I think if Julia shuts down too quickly then the final messages to Sentry don't get sent, which can be particularly relevant if Julia is shutting down immediately after trying to send a message. I think using `atexit` was a work around for this, but maybe its behaviour (or the tasks behaviour) changed in Julia 1.8.

I'll do some tests and get back to you about this next week.

Regardless of the outcome, it might be a good idea to manually call the `clear_queue` function in the outermost scope of the main function.

**Comment by justinmimbs** [comment]
Right on! I think the while loop in `clear_queue` still allows the unsent messages to get picked up and sent on exit; and when the while loop finishes, the channel should be empty. It was just the call to `close` the channel after that that seemed to cause a hang, and that's all I removed. Thanks again!

**Comment by pengwyn** [comment]
It took me a while but I finally got back to this. I'm getting weird behaviour, so I'm just going to write down what I've discovered with the code you put above and a similar one that captures an exception too:

...

No I'm not I just had a silly typo, so I've deleted the essay I just wrote. I think there is some weird interplay with the additional `atexit` function, but I think I just don't understand what the Julia runtime is doing at the end there. But it is irrelevant since your fix works.

Now that I've made sense of it, you're quite right about how it finishes off the queue, so the PR looks good to me! I'll merge it in. Thanks very much!

**Comment by justinmimbs** [comment]
Sure thing! Yeah, it was tricky to make sense of. And I should have been more clear that this fix was a workaround for what seems like a bug elsewhere (the weird interplay during exit). It seems like we _should_ be able to call `close` reliably, but luckily to work around this bug, we didn't need to. Thanks again!

**Pull request merged**
